/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 .\public\kb65_noanimtest.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/kb65_noanimtest.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.49, 0.29, 0.32]} scale={[2.47, 3.19, 2.47]}>
        <mesh geometry={nodes.Plane134.geometry} material={materials.Key} />
        <mesh geometry={nodes.Plane134_1.geometry} material={materials.Board} />
      </group>
    </group>
  )
}

useGLTF.preload('/kb65_noanimtest.gltf')
