/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 .\public\kb65_noanim.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/kb65_noanim.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['2'].geometry} material={materials.Key} position={[-1, 0.29, -0.23]} rotation={[0.04, 0, 0]} scale={[2.47, 3.19, 2.47]} />
      <group position={[0, 0.24, -0.03]} scale={0.99}>
        <mesh geometry={nodes.Plane006.geometry} material={materials.Board} />
        <mesh geometry={nodes.Plane006_1.geometry} material={materials.Key} />
      </group>
      <mesh geometry={nodes['2001'].geometry} material={materials.Key} position={[-0.95, 0.29, -0.09]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2002'].geometry} material={materials.Key} position={[-0.9, 0.29, 0.05]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2003'].geometry} material={materials.Key} position={[-0.87, 0.29, 0.18]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2004'].geometry} material={materials.Key} position={[-1, 0.29, 0.32]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2005'].geometry} material={materials.Key} position={[-0.77, 0.29, 0.05]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2006'].geometry} material={materials.Key} position={[-0.63, 0.29, 0.05]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2007'].geometry} material={materials.Key} position={[-0.49, 0.29, 0.05]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2008'].geometry} material={materials.Key} position={[-0.36, 0.29, 0.05]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2009'].geometry} material={materials.Key} position={[-0.22, 0.29, 0.05]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2010'].geometry} material={materials.Key} position={[-0.08, 0.29, 0.05]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2011'].geometry} material={materials.Key} position={[0.05, 0.29, 0.05]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2012'].geometry} material={materials.Key} position={[0.19, 0.29, 0.05]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2013'].geometry} material={materials.Key} position={[0.32, 0.29, 0.05]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2014'].geometry} material={materials.Key} position={[0.46, 0.29, 0.05]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2015'].geometry} material={materials.Key} position={[0.6, 0.29, 0.05]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2016'].geometry} material={materials.Key} position={[0.86, 0.29, 0.05]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2017'].geometry} material={materials.Key} position={[1, 0.29, 0.05]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2018'].geometry} material={materials.Key} position={[-0.86, 0.29, -0.23]} rotation={[0.04, 0, 0]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2019'].geometry} material={materials.Key} position={[-0.73, 0.29, -0.23]} rotation={[0.04, 0, 0]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2020'].geometry} material={materials.Key} position={[-0.59, 0.29, -0.23]} rotation={[0.04, 0, 0]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2021'].geometry} material={materials.Key} position={[-0.45, 0.29, -0.23]} rotation={[0.04, 0, 0]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2022'].geometry} material={materials.Key} position={[-0.32, 0.29, -0.23]} rotation={[0.04, 0, 0]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2023'].geometry} material={materials.Key} position={[-0.18, 0.29, -0.23]} rotation={[0.04, 0, 0]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2024'].geometry} material={materials.Key} position={[-0.04, 0.29, -0.23]} rotation={[0.04, 0, 0]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2025'].geometry} material={materials.Key} position={[0.09, 0.29, -0.23]} rotation={[0.04, 0, 0]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2026'].geometry} material={materials.Key} position={[0.23, 0.29, -0.23]} rotation={[0.04, 0, 0]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2027'].geometry} material={materials.Key} position={[0.36, 0.29, -0.23]} rotation={[0.04, 0, 0]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2028'].geometry} material={materials.Key} position={[0.5, 0.29, -0.23]} rotation={[0.04, 0, 0]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2029'].geometry} material={materials.Key} position={[0.64, 0.29, -0.23]} rotation={[0.04, 0, 0]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2030'].geometry} material={materials.Key} position={[0.86, 0.29, -0.23]} rotation={[0.04, 0, 0]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2031'].geometry} material={materials.Key} position={[1, 0.29, -0.23]} rotation={[0.04, 0, 0]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2032'].geometry} material={materials.Key} position={[-0.82, 0.29, -0.09]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2033'].geometry} material={materials.Key} position={[-0.68, 0.29, -0.09]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2034'].geometry} material={materials.Key} position={[-0.54, 0.29, -0.09]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2035'].geometry} material={materials.Key} position={[-0.41, 0.29, -0.09]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2036'].geometry} material={materials.Key} position={[-0.27, 0.29, -0.09]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2037'].geometry} material={materials.Key} position={[-0.13, 0.29, -0.09]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2038'].geometry} material={materials.Key} position={[0, 0.29, -0.09]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2039'].geometry} material={materials.Key} position={[0.14, 0.29, -0.09]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2040'].geometry} material={materials.Key} position={[0.27, 0.29, -0.09]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2041'].geometry} material={materials.Key} position={[0.41, 0.29, -0.09]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2042'].geometry} material={materials.Key} position={[0.55, 0.29, -0.09]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2043'].geometry} material={materials.Key} position={[0.68, 0.29, -0.09]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2044'].geometry} material={materials.Key} position={[0.86, 0.29, -0.09]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2045'].geometry} material={materials.Key} position={[1, 0.29, -0.09]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2046'].geometry} material={materials.Key} position={[-0.73, 0.29, 0.18]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2047'].geometry} material={materials.Key} position={[-0.59, 0.29, 0.18]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2048'].geometry} material={materials.Key} position={[-0.46, 0.29, 0.18]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2049'].geometry} material={materials.Key} position={[-0.32, 0.29, 0.18]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2050'].geometry} material={materials.Key} position={[-0.18, 0.29, 0.18]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2051'].geometry} material={materials.Key} position={[-0.05, 0.29, 0.18]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2052'].geometry} material={materials.Key} position={[0.09, 0.29, 0.18]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2053'].geometry} material={materials.Key} position={[0.22, 0.29, 0.18]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2054'].geometry} material={materials.Key} position={[0.36, 0.29, 0.18]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2055'].geometry} material={materials.Key} position={[0.5, 0.29, 0.18]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2056'].geometry} material={materials.Key} position={[0.72, 0.29, 0.18]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2057'].geometry} material={materials.Key} position={[0.86, 0.29, 0.18]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2058'].geometry} material={materials.Key} position={[1, 0.29, 0.18]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2059'].geometry} material={materials.Key} position={[-0.83, 0.29, 0.32]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2060'].geometry} material={materials.Key} position={[-0.66, 0.29, 0.32]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2061'].geometry} material={materials.Key} position={[-0.49, 0.29, 0.32]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2062'].geometry} material={materials.Key} position={[0.31, 0.29, 0.32]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2063'].geometry} material={materials.Key} position={[0.45, 0.29, 0.32]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2064'].geometry} material={materials.Key} position={[0.59, 0.29, 0.32]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2065'].geometry} material={materials.Key} position={[0.72, 0.29, 0.32]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2066'].geometry} material={materials.Key} position={[0.86, 0.29, 0.32]} scale={[2.47, 3.19, 2.47]} />
      <mesh geometry={nodes['2067'].geometry} material={materials.Key} position={[1, 0.29, 0.32]} scale={[2.47, 3.19, 2.47]} />
    </group>
  )
}

useGLTF.preload('/kb65_noanim.glb')
