/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 .\public\kb65_noanimtest.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "react-three-fiber";
import * as THREE from "three";

export default function Model(props) {
  const clock = new THREE.Clock();
  const keyboardRef = useRef();
  useFrame(() => {
    const elapsedTime = clock.getElapsedTime();
    keyboardRef.current.rotation.y = elapsedTime * -0.5;
  });
  const { nodes, materials } = useGLTF("/kb65_noanimtest.gltf");
  return (
    <group {...props} dispose={null} ref={keyboardRef}>
      <group position={[-0.49, 0.29, 0.32]} scale={[2.47, 3.19, 2.47]}>
        <mesh geometry={nodes.Plane134.geometry} material={materials.Key} />
        <mesh geometry={nodes.Plane134_1.geometry} material={materials.Board} />
      </group>
    </group>
  );
}

useGLTF.preload("/kb65_noanimtest.gltf");
