/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 .\public\Lobby_3.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Lobby_3.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.08, 1.44, -0.14]} rotation={[0, 0.05, 0]} scale={3.38}>
        <group position={[0, 0.1, 0]} rotation={[0, Math.PI / 2, 0]} scale={0.22}>
          <mesh geometry={nodes.Cube060.geometry} material={materials.PC_material} />
          <mesh geometry={nodes.Cube060_1.geometry} material={materials.PC_screen} />
          <mesh geometry={nodes.Cube060_2.geometry} material={materials['PC P2']} />
          <mesh geometry={nodes.Cube060_3.geometry} material={materials['Button 2']} />
          <mesh geometry={nodes.Cube060_4.geometry} material={materials['Button 3']} />
          <mesh geometry={nodes.Cube060_5.geometry} material={materials.Button} />
        </group>
      </group>
      <mesh geometry={nodes.Note.geometry} material={materials.STnote2} position={[-0.46, 1.74, 0.07]} rotation={[1.3, -0.08, -0.07]} scale={0.1} />
      <mesh geometry={nodes.Note_2.geometry} material={materials['Atomic Tangerine']} position={[0.27, 2.49, -0.06]} rotation={[1.31, 0.12, -0.09]} scale={0.1} />
      <mesh geometry={nodes.Cup.geometry} material={nodes.Cup.material} position={[0.68, 1.56, -0.07]} />
      <group position={[-0.59, 1.51, 0.47]} rotation={[0, 0.27, 0]} scale={0.52}>
        <mesh geometry={nodes.Plane003.geometry} material={materials['Dum Red']} />
        <mesh geometry={nodes.Plane003_1.geometry} material={materials.Key} />
      </group>
      <group position={[1.09, 1.52, -0.62]} rotation={[0, -0.24, 0]} scale={[0.35, 0.61, 0.61]}>
        <mesh geometry={nodes.Plane005.geometry} material={materials['Early Night']} />
        <mesh geometry={nodes.Plane005_1.geometry} material={materials.Key} />
      </group>
      <mesh geometry={nodes.Keycap.geometry} material={materials.Key} position={[1.04, 1.48, 0.11]} rotation={[0, 0.27, 0]} scale={0.61} />
      <mesh geometry={nodes.Keycap001.geometry} material={materials.Key} position={[1.14, 1.48, 0.08]} rotation={[0, -0.14, 0]} scale={0.61} />
      <mesh geometry={nodes.Keycap002.geometry} material={materials.Key} position={[1.16, 1.47, 0.21]} rotation={[1.66, 0.04, 0.13]} scale={0.61} />
      <mesh geometry={nodes.Keycap003.geometry} material={materials.Key} position={[1.07, 1.48, 0.28]} rotation={[0, -1.48, 0]} scale={0.61} />
      <mesh geometry={nodes.Keycap004.geometry} material={materials.Key} position={[1.32, 1.48, 0.19]} rotation={[Math.PI, -1.25, Math.PI]} scale={0.61} />
      <mesh geometry={nodes.Keycap005.geometry} material={materials.Key} position={[1.22, 1.47, 0.3]} rotation={[1.59, 0.09, 1.09]} scale={0.61} />
      <mesh geometry={nodes.KBJ_2.geometry} material={materials['Pickled Bluewood']} position={[-1.11, 1.47, -0.4]} rotation={[0, -0.62, 0]} scale={0.36} />
      <mesh geometry={nodes.KBJ_3.geometry} material={materials.Crusta} position={[0.44, 1.84, -0.36]} rotation={[3.12, -0.1, -1.73]} scale={0.36} />
      <mesh geometry={nodes.BezierCurve.geometry} material={materials['Soft Black']} position={[-0.56, 1.54, -0.14]} />
      <mesh geometry={nodes.Desk.geometry} material={materials.Creamy} position={[0, 1.25, 0]} scale={[0.72, 1, 1]} />
      <group position={[-1.34, 0.38, 0.68]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.Creamy} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Soft Black']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Silver Matte']} />
        <group position={[2.66, 0, 0]}>
          <mesh geometry={nodes.Cylinder002_1.geometry} material={materials.Creamy} />
          <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Soft Black']} />
          <mesh geometry={nodes.Cylinder002_3.geometry} material={materials['Silver Matte']} />
        </group>
        <group position={[-0.01, 0, -1.38]}>
          <mesh geometry={nodes.Cylinder003_1.geometry} material={materials.Creamy} />
          <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Soft Black']} />
          <mesh geometry={nodes.Cylinder003_3.geometry} material={materials['Silver Matte']} />
        </group>
        <group position={[2.68, 0, -1.37]}>
          <mesh geometry={nodes.Cylinder004_1.geometry} material={materials.Creamy} />
          <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['Soft Black']} />
          <mesh geometry={nodes.Cylinder004_3.geometry} material={materials['Silver Matte']} />
        </group>
      </group>
      <group position={[0.53, 1.45, 0.65]} rotation={[0, -0.15, 0]} scale={0.38}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['Dum Red']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Soft Black']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Beige?']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Lobby_3.gltf')
