/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 .\public\lobby.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/lobby.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.8, 0]} rotation={[0, Math.PI / 2, 0]} scale={0.22}>
        <mesh geometry={nodes.Cube060.geometry} material={materials.PC_material} />
        <mesh geometry={nodes.Cube060_1.geometry} material={materials.PC_screen} />
        <group position={[-0.01, -0.8, 0.06]} rotation={[0, 0, 0.06]} scale={[0.04, 0.04, 0.1]}>
          <mesh geometry={nodes.Cube071.geometry} material={materials['PC P2']} />
          <mesh geometry={nodes.Cube071_1.geometry} material={materials['Button 2']} />
          <mesh geometry={nodes.Cube071_2.geometry} material={materials['Button 3']} />
          <mesh geometry={nodes.Cube071_3.geometry} material={materials.Button} />
          <mesh geometry={nodes.Cube071_4.geometry} material={materials.PC_material} />
        </group>
      </group>
      <mesh geometry={nodes.lobby.geometry} material={materials.Random} position={[0, 1.64, 0]} scale={1.07} />
    </group>
  )
}

useGLTF.preload('/lobby.glb')
