/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 .\public\Monitor.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Monitor.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[0, Math.PI / -1, 0]} scale={[0.01, 0.01, 0.02]}>
        <mesh geometry={nodes.Cube071.geometry} material={materials['PC P2']} />
        <mesh geometry={nodes.Cube071_1.geometry} material={materials['Button 2']} />
        <mesh geometry={nodes.Cube071_2.geometry} material={materials['Button 3']} />
        <mesh geometry={nodes.Cube071_3.geometry} material={materials.Button} />
        <mesh geometry={nodes.Cube071_4.geometry} material={materials.PC_material} />
        <mesh geometry={nodes.Cube071_5.geometry} material={materials.PC_screen} />
      </group>
    </group>
  )
}

useGLTF.preload('/Monitor.glb')
